// export const SIGNIN_USER = 'SIGNIN_USER';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const UNAUTENTICATED_USER = 'UNAUTENTICATED_USER';
export const AUTEHNTICATION_ERROR = 'AUTEHNTICATION_ERROR';